### ISSUE TITLE
datasource "sonarqube_permission_template"

### ISSUE THREAD

**Issue by eugeis** [jdamata/terraform-provider-sonarqube#148]
Hi, 

thank you for your great provider!

It would be great to hava datasources by name for:

like

datasource "sonarqube_permission_template" example {
  name = <name of permission_template>
}

then I could use it by 'sonarqube_permissions' for template_id

or

resource "sonarqube_permissions" example {
 ...
  template = <name> (not only template_id)
}

Thank You
Eugen

**Comment by jdamata** [comment]
Are you creating the template via terraform? I think you would be able to access the output of the template resource to get its ID or name. Otherwise yah a data resource for this sounds good to me. Did you want to work on this? Data resources are pretty low code and easy IE: https://github.com/jdamata/terraform-provider-sonarqube/pull/169

**Comment by jdamata** [comment]
@eugeis did that answer your question? If not please reopen the issue.
