### ISSUE TITLE
Massive project KEY updates

### ISSUE THREAD

**Issue by marcin-sowa** [jdamata/terraform-provider-sonarqube#244]
Let's say we have yaml file with 100 projects to create by provider:

```
 - project A with ID 1234
 - project B with D 34
 - project C with ID 56
 - ....
 - project CCC
```

Someone removes "project B"
Current implementation will set `sonarqube_project.project[2] project KEY to "project C" but keep project ID 34.

So it will replace all following projects with the content of another project.
The issue is in this code: https://github.com/jdamata/terraform-provider-sonarqube/blob/master/sonarqube/resource_sonarqube_project.go

```
// handle project key updates (api/projects/update_key)
if d.HasChange("project") {
	oldKey, newKey := d.GetChange("project")

	sonarQubeURL := m.(*ProviderConfiguration).sonarQubeURL
	sonarQubeURL.Path = strings.TrimSuffix(sonarQubeURL.Path, "/") + "/api/projects/update_key"
	sonarQubeURL.RawQuery = url.Values{
		"from": []string{oldKey.(string)},
		"to":   []string{newKey.(string)},
	}.Encode()

	resp, err := httpRequestHelper(
		m.(*ProviderConfiguration).httpClient,
		"POST",
		sonarQubeURL.String(),
		http.StatusNoContent,
		"resourceSonarqubeProjectUpdate",
	)
	if err != nil {
		return fmt.Errorf("error updating Sonarqube project key: %+v", err)
	}
	defer resp.Body.Close()

	// Update the id like in github provider (https://github.com/integrations/terraform-provider-github/blob/b7e63d63c59b9b1df9c6d05204bdaa1b349e8c8a/github/resource_github_repository.go#L746-L750)
	d.SetId(newKey.(string))
```

Expected implementation should check if new project KEY exist and replace just project ID in state after checking by project KEY.
So, first should be GET to check for project and if not found then POST to update project KEY.

**Comment by freeranger** [comment]
Hi

A couple of questions for you:
1. You imply that it is a problem with large lists of projects - but, if it is an issue, why wouldn't it be an issue with a small number of projects, say 3 or 4?
2. Can you provide a reproducible example with actual terraform code?
3. Are you suffering from the sorts of problems described here: https://jeffbrown.tech/terraform-for-each-index/

From your reference to `sonarqube_project.project[2]`, it suggests you are doing index based rather than key based looping so you will likely get problems anyway with resources being deleted and recreated when you don't want that to happen.

**Comment by marcin-sowa** [comment]
This is real reason for using map instead of collection.

Used your advice, all working now ;).
Thanks.
