### ISSUE TITLE
[Feature] Data source for all users, optionally filtered by parameters

### ISSUE THREAD

**Issue by brianphillips** [jdamata/terraform-provider-sonarqube#265]
I would like to be able to pull all existing users back from Sonarqube so that I can properly map the group membership information from a third party system into Sonarqube. I would need to create a map of email address to `login_name` (so that I can then use the appropriate `login_name` for creating `sonarqube_group_member` resources) but I need to be able to pull back the full (or filtered) collection of users and not just one by one using the `login_name` to look them up as is currently supported.

This would use the following API endpoint: https://next.sonarqube.com/sonarqube/web_api_v2#/users-management/users--get

One caveat is that the v2 API is only available starting with v10.1.

Is this something you'd be open to accepting a PR for?

**Comment by freeranger** [comment]
Hi

I think using the v2 API at the moment would just create a lot of pain in terms of having to support both APIs at once because not everyone will be on the latest, greatest.
I think the repo owner would need to consider a strategy for supporting V2 going forward (try to support both versions of the provider?  Just make a breaking change and the old version is frozen?  etc

It seems like https://next.sonarqube.com/sonarqube/web_api/api/permissions/users?internal=true would give you what you need - yes it is "internal" but it is a v1 API end point.

Also whilst I think it is good to add more features to this provider, you don't *have* to add features to the provider in order to do what you want.  You could create a http data source to get what you need for your specific purpose.
It would be nice to be able to manage and retrieve users via the provider though :)

**Comment by brianphillips** [comment]
Yes, I ended up using the http provider. Thanks for considering the feature request!
